name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - hoomd: 2.9.2
            tensorflow: 2.3.0
            tbb-devel: 2020.1
          - hoomd: 2.9.0
            tensorflow: 2.3.0
            tbb-devel: 2020.1
          - hoomd: 2.8.2
            tensorflow: 2.3.0
            tbb-devel: 2020.1
          - hoomd: 2.7.0
            tensorflow: 2.3.0
            tbb-devel: 2019.8
          - hoomd: 2.6.0
            tensorflow: 2.3.0
            tbb-devel: 2019.7

    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1.0.3
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        # Install testing dependencies
        pip install pytest-cov pytest-xdist
        
        # Install software dependencies
        pip install tensorflow==${{ matrix.tensorflow }}
        conda install -c conda-forge tbb-devel==${{ matrix.tbb-devel }} hoomd==${{ matrix.hoomd }}
    - name: Download and install HTF
      run: |
        mkdir build && cd build
        CXX=g++ CC=gcc CMAKE_PREFIX_PATH=/usr/share/miniconda cmake ..
        make install
        cd ..
    - name: Run tests
      run: |
        pytest -v --forked